- id: openbook
  type: group
  role: [openbook]
  tasks:
    - hiera
    - globals
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start,controller]
  parameters:
    strategy:
      type: parallel
