- id: openbook
  type: group
  role: [openbook]
  tasks:
    - hiera
    - globals
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start,controller]
  parameters:
    strategy:
      type: parallel

# Configure haproxy on OpenStack Controllers
#- id: openstack-haproxy-openbook
#  type: puppet
#  groups: [primary-controller, controller]
#  required_for: [deploy_end]
#  requires: [deploy_start, openstack-haproxy, rabbitmq]
#  parameters:
#    puppet_manifest: puppet/manifests/controller-vip.pp
#    puppet_modules: puppet/modules:/etc/puppet/modules
#    timeout: 720

