attributes:
  metadata:
    restrictions:
        - condition: "settings:additional_components.ceilometer.value == false"
          strict: true
          message: "Ceilometer (OpenStack Telemetry) is required and must be enabled in the environment"
          action: "disable"
  
  openbook_text:
    value: 'Openbook Fuel Plugin'
    label: 'Openbook plugin'
    description: 'Deploys Openbook for billing/invoicing and customer lifecycle management for OpenStack'
    weight: 25
    type: "text"
  db_password:
    value: "Tall!g3nt"
    label: "database password"
    description: "Password for MariaDB"
    weight: 30
    type: "password"
  node_name:
    value: 'openbook'
    label: 'Node name'
    description: 'The name of the node where the plugin will be deployed.'
    weight: 10
    type: "text"
  
  sharefile_user:
    type: "text"
    weight: 50
    value: ""
    label: "Sharefile Username (e-mail)"
    description: "Sharefile username is required to download Openbook"
    regex: &email
      source: '[a-z0-9!#$%&*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.?)?[a-z0-9]?(?:[a-z0-9-]*[a-z0-9])?'
      error: "Invalid email address"
  
  sharefile_pass:
    type: "password"
    weight: 51
    value: ""
    label: "Sharefile Password"
    description: "Sharefile password is required to download Openbook"
    regex: &not_empty_parameter
      source: '\S'
      error: "Invalid value"
  
  jvm_heap_size:
    value: '1'
    label: 'JVM heap size'
    description: 'in GB (between 1 and 32). The amount of memory reserved for the JVM.'
    weight: 100
    type: "text"
    regex:
      source: '^([1-9]|[12][0-9]|3[0-2])$'
      error: 'Enter a value between 1 and 32'

